jobs:
    - name: zephyr_runDocs
      type: runSh
      steps:
        - IN: zephyr-repo
        - IN: zephyr-docker
        - TASK:
           - script: ls -lR /build/IN
           - script: . /build/IN/zephyr-repo/gitRepo/scripts/ci/build-docs.sh

    - name: zephyr_runCI
      type: runCI
      steps:
        - IN: daily-verify-trigger
        - IN: code-scan-trigger
        - IN: zephyr_runDocs
