jobs:
    - name: zephyr_runDocs
      type: runSh
      steps:
        - IN: zephyr-repo
        - IN: zephyr-docker
        - IN: nightly-trigger
        - TASK:
           - script: ls -la /build/IN
           - script: ls -la /build/IN/nightly-trigger
           - script: . /build/IN/zephyr-repo/gitRepo/scripts/ci/build-docs.sh

    - name: zephyr_runCI
      type: runCI
      steps:
        - IN: zephyr_runDocs
