jobs:
    - name: zephyr_runDocs
      type: runSh
      steps:
        - IN: zephyr-repo
        - IN: zephyr-docker
        - OUT: zephyr_ciRepo
        - TASK:
           - script: env
           - script: . /build/IN/zephyr-repo/gitRepo/scripts/ci/build-docs.sh

    - name: zephyr_run_daily
      type: runSh
      steps:
        - IN: daily-verify
        - TASK:
           - script: echo "Running daily job"
           - script: mkdir -p ${ZEPHYR_RUN_DAILY_STATE}/${RESOURCE_ID} ${ZEPHYR_RUN_DAILY_STATE}/DONE
           - script: echo 'PLATFORMS="--all"' >> ${ZEPHYR_RUN_DAILY_STATE}/${RESOURCE_ID}/job.env
           - script: env

    - name: zephyr_run_code_scan
      type: runSh
      steps:
        - IN: code-scan
        - TASK:
           - script: echo "Running code scan"
           - script: echo 'PLATFORMS="--all"' >> ${ZEPHYR_RUN_CODE_SCAN_STATE}/job.env

    - name: zephyr_runCI
      type: runCI
      steps:
        - IN: zephyr_run_code_scan
        - IN: zephyr_run_daily
        - IN: zephyr_runDocs
