jobs:
    - name: zephyr_runDocs
      type: runSh
      steps:
        - IN: zephyr-repo
          showBuildStatus: true
        - OUT: zephyr_ciRepo
        - OUT: trigger_by
        - TASK:
           - script: env
           - script: . /build/IN/zephyr-repo/gitRepo/scripts/ci/build-docs.sh

    - name: zephyr_run_daily
      type: runSh
      steps:
        - IN: daily-verify
        - OUT: trigger_by
        - TASK:
           - script: echo "Running daily job"
           - script: echo "BUILD_NUMBER=${BUILD_NUMBER}" > ${JOB_STATE}/trigger_by.ENV
           - script: echo "JOB_TRIGGERED_BY_NAME_HACK=${JOB_TRIGGERED_BY_NAME}" > ${JOB_STATE}/trigger_by.ENV
           - script: env

    - name: zephyr_run_code_scan
      type: runSh
      steps:
        - IN: code-scan
        - OUT: trigger_by
        - TASK:
           - script: echo "Running code scan"
           - script: echo "BUILD_NUMBER=${BUILD_NUMBER}" > ${JOB_STATE}/trigger_by.ENV
           - script: echo "JOB_TRIGGERED_BY_NAME_HACK=${JOB_TRIGGERED_BY_NAME}" > ${JOB_STATE}/trigger_by.ENV
           - script: env

    - name: zephyr_runCI
      type: runCI
      steps:
        - IN: trigger_by
        - IN: zephyr_ciRepo
          switch: off
